package com.robberwick.papertap.waveshare

/**
 * Single source of truth for every supported WaveShare NFC e-paper model.
 *
 * Protocol selectors, payload sizes, and packet counts are cross-checked against
 * proxmark3's WaveShare implementation (`client/src/cmdhfwaveshare.c`), which is
 * derived from WaveShare's ST25R3911B NFC demo. Physical resolutions are checked
 * against WaveShare specifications. Only [ONE_54_B] is hardware-verified in
 * PaperTap; all other models stay behind the experimental-model setting.
 *
 * [width] and [height] are the landscape bitmap dimensions generated by
 * PaperTap. [needsRotation] converts that bitmap to the controller's native
 * scan orientation before packing.
 */
enum class DisplayModel(
    val preferenceValue: String,
    val label: String,
    val width: Int,
    val height: Int,
    val modelSelectByte: Byte?,
    val dataBytesPerPacket: Int,
    val packetCount: Int,
    val protocol: Protocol,
    val needsRotation: Boolean = false,
    val trailingPadding: Boolean = false,
    val readyPollDelayMs: Long = 300,
) {
    TWO_13(
        preferenceValue = "2.13",
        label = "2.13\"",
        width = 250,
        height = 122,
        modelSelectByte = 4,
        dataBytesPerPacket = 16,
        packetCount = 250,
        protocol = Protocol.SINGLE_PASS,
        needsRotation = true,
    ),
    TWO_9(
        preferenceValue = "2.9",
        label = "2.9\"",
        width = 296,
        height = 128,
        modelSelectByte = 7,
        dataBytesPerPacket = 16,
        packetCount = 296,
        protocol = Protocol.SINGLE_PASS,
    ),
    FOUR_2(
        preferenceValue = "4.2",
        label = "4.2\"",
        width = 400,
        height = 300,
        modelSelectByte = 10,
        dataBytesPerPacket = 100,
        packetCount = 150,
        protocol = Protocol.SINGLE_PASS,
    ),
    SEVEN_5(
        preferenceValue = "7.5",
        label = "7.5\"",
        width = 800,
        height = 480,
        modelSelectByte = 14,
        dataBytesPerPacket = 120,
        packetCount = 400,
        protocol = Protocol.SINGLE_PASS,
    ),
    TWO_7(
        preferenceValue = "2.7",
        label = "2.7\"",
        width = 264,
        height = 176,
        modelSelectByte = 16,
        dataBytesPerPacket = 121,
        packetCount = 48,
        protocol = Protocol.BLANK_THEN_BLACK,
        needsRotation = true,
    ),
    TWO_13_B(
        preferenceValue = "2.13_b",
        label = "2.13\" B (black / white / red)",
        width = 212,
        height = 104,
        modelSelectByte = 5,
        dataBytesPerPacket = 106,
        packetCount = 26,
        protocol = Protocol.DUAL_LAYER,
        needsRotation = true,
        readyPollDelayMs = 9_000,
    ),
    ONE_54_B(
        preferenceValue = "1.54_b",
        label = "1.54\" B (black / white / red)",
        width = 200,
        height = 200,
        modelSelectByte = null,
        dataBytesPerPacket = 100,
        packetCount = 50,
        protocol = Protocol.ONE_54_B,
    ),
    SEVEN_5_HD(
        preferenceValue = "7.5_hd",
        label = "7.5\" HD",
        width = 880,
        height = 528,
        modelSelectByte = 17,
        dataBytesPerPacket = 120,
        packetCount = 484,
        protocol = Protocol.SINGLE_PASS,
        trailingPadding = true,
        readyPollDelayMs = 1_000,
    );

    val isHardwareVerified: Boolean
        get() = this == ONE_54_B

    fun matchesDimensions(bitmapWidth: Int, bitmapHeight: Int): Boolean {
        return (bitmapWidth == width && bitmapHeight == height) ||
            (bitmapWidth == height && bitmapHeight == width)
    }

    enum class Protocol {
        SINGLE_PASS,
        BLANK_THEN_BLACK,
        DUAL_LAYER,
        ONE_54_B,
    }

    companion object {
        const val DEFAULT_PREFERENCE_VALUE = "1.54_b"

        fun fromPreference(value: String?): DisplayModel? {
            return entries.firstOrNull { model ->
                model.preferenceValue == value || model.label == value
            }
        }

        fun selectable(includeExperimental: Boolean): List<DisplayModel> {
            return if (includeExperimental) entries.toList() else listOf(ONE_54_B)
        }
    }
}
